config/routes.rb
Careerfoundry::Application.routes.draw do

  root 'pages#landing_page'

 
  get 'about', to: "pages#about"

  get 'contact',   to: 'form_example#form_input'
  get 'contact_thanks',  to: 'form_example#form_output'

  resources :products do
    resources :testimonials
  end
  
  resources :posts do
    resources :comments
  end

 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :testimonials
	validates :name, presence: true
	validates :description, presence: true, length: { in: 20..200 }
	validates :price, presence: true
	validates :image_url, presence: true
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    	@post = Post.find(params[:post_id])
    	@comment = @post.comments.create(comment_params)
    	redirect_to post_path(@post)
  	end
 
	private
		def comment_params
	      params.require(:comment).permit(:commenter, :body)
	    end
end

app/controllers/form_example_controller.rb
class FormExampleController < ApplicationController
  def form_input
  end

  def form_output
  	ContactMailer.thankyou_email(params).deliver
  	ContactMailer.sent_email(params).deliver
  	render "form_result"

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing_page
    @featured_product1 = Product.find(1)
    @featured_product2 = Product.find(2)


    @latest_posts = Post.all(:limit => 3, :order => "created_at DESC")
  end

  def contact
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
 
 		if @post.save
		  redirect_to @post
		else 
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def index
		@posts = Post.all(:order => "created_at DESC")
	end

	def edit
  		@post = Post.find(params[:id])
	end

	def update
	  @post = Post.find(params[:id])
	 
	  if @post.update(post_params)
	    redirect_to @post
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @post = Post.find(params[:id])
	  @post.destroy
	 
	  redirect_to posts_path
	end

	private
	  def post_params
	    params.require(:post).permit(:title, :text)
	  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end



  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.where(name: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
	def create
    	@product = Product.find(params[:product_id])
    	@testimonial = @product.testimonials.create(testimonial_params)
    	redirect_to product_path(@product)
  	end
 
	private
		def testimonial_params
	      params.require(:testimonial).permit(:name, :body, :email)
	    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/application/_footer.html.erb
<footer>
	&copy; Michael P. Navarro -- 2014
</footer>

</body>
</html>

app/views/application/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Careerfoundry</title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img class="logo-sm" src="/images/mnlogo.png"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <li><%= link_to 'My Blog', controller: 'posts' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/form_example/form_input.html.erb
<div class="container-inner">
	<h1>Contact Us</h1>

	<%= form_tag(contact_thanks_path, method: "get") do %>
	  <p>
	  	<%= label_tag(:name, "Name:") %>
	  	<%= text_field_tag(:name) %>
	  </p>
	  <p>
	  	<%= label_tag(:email, "E-mail:") %>
	  	<%= text_field_tag(:email) %>
	  </p>
	  <p>
	  	<%= label_tag(:message, "Message:") %>
	  	<%= text_area_tag(:message) %>
	  </p>
	  <p>
	  	<%= submit_tag("Submit") %>
	  </p>
	<% end %>

</div>

app/views/form_example/form_result.html.erb
<div class="container-inner">
	<h1>Contact Us</h1>
	<p>Thanks <%= params[:name] %>, your message has been sent and we will contact you soon!</p>
</div>

app/views/layouts/application.html.erb
<%= render 'header' %>

<%= yield %>

<%= render 'footer' %>

app/views/pages/_featured_product.html.erb
<div class="jumbotron" style="
	background: url('<%= @featured_product1.image_url %>') no-repeat center center fixed !important;
	  -webkit-background-size: cover !important;
	  -moz-background-size: cover !important;
	  -o-background-size: cover !important;
	  background-size: cover !important;
	-webkit-box-shadow: 0px 5px 10px 10px rgba(0, 0, 0, 0.75);
	-moz-box-shadow:    0px 5px 10px 10px rgba(0, 0, 0, 0.75);
	box-shadow:         0px 5px 10px 10px rgba(0, 0, 0, 0.75);
	">
  <div class="container">
	  <h1><%= @featured_product1.name %></h1>
	  <p><%= @featured_product1.description %></p>
	  <p><%= link_to 'Read More...', @featured_product1, {:class => "btn btn-danger btn-lg", :role => "button"} %></p>
  </div>
</div>

<div class="jumbotron" style="
	background: url('<%= @featured_product2.image_url %>') no-repeat center center fixed !important;
	  -webkit-background-size: cover !important;
	  -moz-background-size: cover !important;
	  -o-background-size: cover !important;
	  background-size: cover !important;
    -webkit-box-shadow: 0px 5px 10px 0px rgba(0, 0, 0, 0.75);
    -moz-box-shadow:    0px 5px 10px 0px rgba(0, 0, 0, 0.75);
    box-shadow:         0px 5px 10px 0px rgba(0, 0, 0, 0.75);
	">
  <div class="container">
	  <h1><%= @featured_product2.name %></h1>
	  <p><%= @featured_product2.description %></p>
	  <p><%= link_to 'Read More...', @featured_product2, {:class => "btn btn-danger btn-lg", :role => "button"} %></p>
  </div>
</div>

app/views/pages/about.html.erb
<div class="container-inner">
	<h1>About Michael's Magazine</h1>


	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu purus facilisis, vulputate leo sit amet, malesuada nibh. Sed et varius libero. Quisque porta justo ac magna adipiscing pharetra et in nibh. Maecenas ornare enim eget sem aliquet, auctor commodo augue pellentesque. Vestibulum sodales metus eu nisi lobortis fermentum. Nulla tellus arcu, fringilla in justo id, imperdiet dignissim tortor. Sed sit amet nunc malesuada, fermentum augue nec, elementum sem. Donec sodales neque libero, et convallis tortor molestie vitae. Ut bibendum condimentum urna eu consectetur. Nulla fringilla ante vel nisi sollicitudin, et lobortis nulla dignissim. Nunc consectetur ipsum in arcu ullamcorper, porttitor cursus quam aliquam. In viverra id arcu non bibendum. Nunc ultricies ligula non massa ultrices mollis. Morbi hendrerit tellus a aliquam vestibulum. Quisque non sapien erat. Pellentesque eleifend vel augue in elementum.</p>
	<p>Quisque purus magna, porta et felis vel, tincidunt iaculis nunc. Fusce in nibh fermentum, semper libero quis, varius ante. Vestibulum leo arcu, feugiat et nibh in, sodales gravida purus. Fusce sodales vehicula orci in accumsan. In molestie lacus et ipsum dignissim, ut venenatis felis volutpat. Nam id lacus mi. Maecenas eget orci posuere, viverra risus consectetur, aliquam magna.</p>
	<p>Ut commodo lacus tellus. Fusce gravida, turpis in pharetra mollis, libero felis dapibus turpis, eget pulvinar diam erat at felis. Etiam lacinia condimentum est ac hendrerit. Integer adipiscing gravida velit, in scelerisque nulla ornare volutpat. In ut fermentum sem. Praesent at purus et nunc vestibulum malesuada. Proin dignissim aliquam posuere. Cras tincidunt sem eget consectetur volutpat. Donec eu pharetra enim. Donec sed placerat orci. Curabitur in varius diam. Proin in erat vel metus pulvinar euismod. Vivamus id convallis leo. Vestibulum non sapien vulputate mi condimentum venenatis ultrices non leo. Nulla posuere consectetur felis ac posuere.</p>
	<p>Donec id sollicitudin urna, a tincidunt odio. Duis aliquet mauris dolor, et dictum purus accumsan a. Sed pretium tincidunt dolor id mollis. Integer diam neque, commodo in enim quis, fringilla venenatis lorem. Ut ornare quam risus, at dictum metus condimentum sit amet. Morbi eu nulla vulputate, dignissim tortor sed, fringilla libero. Donec nisi lacus, accumsan malesuada ornare eu, cursus id mauris. Donec iaculis orci eget risus facilisis, et aliquam augue tincidunt. Integer id tellus lectus. Pellentesque sagittis dui eros, tempus feugiat urna feugiat a. Aenean neque libero, volutpat ut fringilla id, tincidunt ut nisl. Suspendisse sed molestie sem. Aenean posuere congue elementum. Suspendisse dapibus venenatis nibh ut dignissim. Morbi vitae laoreet arcu, eu imperdiet orci.</p>
	<p>Sed orci sapien, tempus non massa eget, tempus varius leo. Aliquam euismod, nisi sed sollicitudin accumsan, risus nisi cursus justo, eget suscipit velit nisi dignissim lacus. Nullam placerat massa in lacus eleifend, non scelerisque leo pretium. In eros lacus, porttitor id tincidunt in, faucibus at libero. Duis eu ullamcorper nunc. Morbi vestibulum sapien fermentum felis venenatis viverra. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
</div>

app/views/pages/contact.html.erb
<div class="container-inner">
	<h1>Contact Infomation</h1>
	<p>Email: mpn123@gmail.com</p>
	<p>Phone: +49 15257080458</p>
	<p>Frobenstr 22</p>
	<p>10783 Berlin, DE</p>
</div>

app/views/pages/landing_page.html.erb
<div class="jumbotron">
  <div class="container">
	  <h1>Michael's Magazine</h1>
	  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu purus facilisis, vulputate leo sit amet, malesuada nibh. Sed et varius libero. Quisque porta justo ac magna adipiscing pharetra et in nibh. Maecenas ornare enim eget sem aliquet, auctor commodo augue pellentesque. Vestibulum sodales metus eu nisi lobortis fermentum. Nulla tellus arcu, fringilla in justo id, imperdiet dignissim tortor. Sed sit amet nunc malesuada, fermentum augue nec, elementum sem. Donec sodales neque libero, et convallis tortor molestie vitae. Ut bibendum condimentum urna eu consectetur. Nulla fringilla ante vel nisi sollicitudin, et lobortis nulla dignissim. Nunc consectetur ipsum in arcu ullamcorper, porttitor cursus quam aliquam. In viverra id arcu non bibendum. Nunc ultricies ligula non massa ultrices mollis. Morbi hendrerit tellus a aliquam vestibulum. Quisque non sapien erat. Pellentesque eleifend vel augue in elementum.</p>
	  <p><a class="btn btn-danger btn-lg" role="button">Learn more</a></p>
  </div>
</div>

<%= render 'featured_product' %>

<div class="container spotlight">
	<div class="row">
	<div class="col-md-4 col-md-offset-2">
		<div class="thumbnail">
		    <img src="/images/mag_may.jpg" class="mag_thumb" alt="...">
		    <div class="caption">
		        <h3>Contact information.</h3>
		    	<p><a href="/pages/contact" class="btn btn-danger" role="button">Read More...</a></p>
		  	</div>
	 	</div>
	</div>
	<div class="col-md-4">
		<div class="thumbnail">
		    <img src="/images/mag_june.jpg" class="mag_thumb" alt="...">
		    <div class="caption">
		        <h3>About the magazine.</h3>
		    	<p><a href="/pages/about" class="btn btn-danger" role="button">Read More...</a></p>
		  	</div>
	 	</div>
	 </div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="landing_header"><%= link_to "Recent Blog Posts", controller: 'posts' %></div>
			<% @latest_posts.each do |post| %>
		      <div class="post">
		        <div class="post_title">
		          <%= link_to post.title, post_path(post) %>
		        </div>
		      </div>
		    <% end %>
		</div>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div class="container-inner">
  <h1>Edit post</h1>
 
  <%= render 'form' %>
   
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container-inner">
  <h1>Listing posts</h1>
   
  
   
    <% @posts.each do |post| %>
      <div class="post">
        <div class="post_title">
          <%= link_to post.title, post_path(post) %>
        </div>
        <div class="post_text">
          <%= post.text %>
        </div>

        <div class="post_edit">
          <%= link_to 'Edit', edit_post_path(post) %> |
          <%= link_to 'Destroy', post_path(post),
                      method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %>

    <div class="post_btn">
      <%= link_to 'New post', new_post_path %>
    </div>

</div>

app/views/posts/new.html.erb
<div class="container-inner">
  <h1>New post</h1>
 
  <%= render 'form' %>
   
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container-inner">


	<div class="post">
        <div class="post_title"><%= @post.title %></div>
	  	<div class="post_text"><%= @post.text %></div>
	  	<div class="post_edit"><%= link_to 'Edit', edit_post_path(@post) %></div>
	</div>

	<div class="post_comments">
		<div class="landing_header">Comments</div>
		<% @post.comments.each do |comment| %>
		    <div class="post">
       			<div class="post_title"><%= comment.commenter %></div>
		    	<div class="post_text"><%= comment.body %></div>
		    </div>
		<% end %>
		
		<div class="landing_header">Add a Comment</div>
		<%= form_for([@post, @post.comments.build]) do |f| %>
		  <div class="post">
		  	<table>
		  		<tr>
			    	<td><%= f.label :commenter %></td>
			    	<td><%= f.label :body %></td>
			    </tr>
			    <tr>
			    	<td><%= f.text_field :commenter %></td>
			   		<td><%= f.text_area :body %></td>
				</tr>
			 </table>
		    <%= f.submit 'Add Comment', :class => 'btn btn-danger' %>
		   </div>
		<% end %>
	</div>

	<div class="post_btn">
		<%= link_to 'Back', posts_path %>
	</div>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    &euro;<%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container-inner">

  <h1>Listing products</h1>
  <div class="container no-padding">
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-4 product-outer">
          <div class="product-inner">
            <h1><%= link_to product.name, product %></h1>
            <p><%= product.description %></p>
            <p><%= number_to_currency(product.price, locale: :de) %></p>
            <p><img src="<%= product.image_url %>"></p>
            <div class="product-admin"> 
              <%= link_to 'Edit', edit_product_path(product) %><br>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <br>

  <p><%= link_to 'New Product', new_product_path, {:class => "btn btn-danger btn-lg", :role => "button"} %></p>

</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container-inner">

	<p id="notice"><%= notice %></p>

	<div class="product-inner">
	  <h1><%= @product.name %></h1>
	  <p><%= @product.description %></p>
	  <p><img src="<%= @product.image_url %>"></p>
	  <p><%= number_to_currency(@product.price, locale: :de) %></p>
	 </div>

	 <div class="post_comments">
		<div class="landing_header">Testimonials</div>
		<% @product.testimonials.each do |testimonial| %>
		    <div class="post">
       			<div class="post_title"><%= testimonial.name %></div>
		    	<div class="post_text"><%= testimonial.body %></div>
		    </div>
		<% end %>
		
		<div class="landing_header">Add a Testimonial</div>
		<%= form_for([@product, @product.testimonials.build]) do |f| %>
		  <div class="post">
		  	<table>
		  		<tr>
			    	<td><%= f.label :name %></td>
			    	<td><%= f.label :email %></td>
			    	<td><%= f.label :body %></td>
			    </tr>
			    <tr>
			    	<td><%= f.text_field :name %></td>
			    	<td><%= f.text_field :email %></td>
			   		<td><%= f.text_area :body %></td>
				</tr>
			 </table>
		    <%= f.submit 'Add Testimonial', :class => 'btn btn-danger' %>
		   </div>
		<% end %>
	</div>

	<%= link_to 'Edit', edit_product_path(@product), {:class => "btn btn-danger btn-lg", :role => "button"} %>
	<%= link_to 'Back', products_path, {:class => "btn btn-danger btn-lg", :role => "button"} %>
</div>